name: build-test

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - 'main'
    paths:
      - 'build/Dockerfile'

  workflow_dispatch:
  
jobs:
  
  test:
    uses: ./.github/workflows/test.yml
    with:
      dockerfile: Dockerfile
      dockerfile_folder: helix-swarm
    secrets: inherit