name: build-test

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - 'main'
    paths:
      - 'build/Dockerfile'

  workflow_dispatch:
  
jobs:
  
  test:
    uses: ./.github/workflows/test.yml
    with:
      docker_files_name: Dockerfile
      version: ${{ vars.VERSION }}
      user: ${{ secrets.USER }}
    secrets: inherit