name: build-auth-svc

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - 'main'

  workflow_dispatch:
  
jobs:
  
  test:
    uses: ./.github/workflows/test.yml
    with:
      # The Dockerfile to build
      dockerfile: Dockerfile
      image_name: helix-auth-svc
      version: 2024.2
    secrets: inherit

  push:
    uses: ./.github/workflows/publish.yml
    needs: test
    with:
      # The Dockerfile to build
      dockerfile: Dockerfile
      image_name: helix-auth-svc
      version: 2024.2
    secrets: inherit
