name: publish

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      dockerfile_folder:
        required: true
        type: string
      image_name:
        required: true
        type: string
      version:
        required: true
        type: string
      version_substr:
        type: string

jobs:

  # Publish image to GitHub Container Registry
  # https://docs.github.com/en/packages/guides/pushing-and-pulling-docker-images
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
            docker build \
            -f ./${{ inputs.dockerfile_folder }}/${{ inputs.dockerfile }} ./${{ inputs.dockerfile_folder }} \
            -t ${{ inputs.image_name }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/${{ inputs.image_name }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          TAG_SUFFIX=""
          if [ "${{ github.event_name }}" == "schedule" ]; then
            TAG_SUFFIX="nightly"
            docker tag ${{ inputs.image_name }} $IMAGE_ID:$TAG_SUFFIX
            docker push $IMAGE_ID:$TAG_SUFFIX
          fi

          docker tag ${{ inputs.image_name }} $IMAGE_ID:$CURRENT_DATETIME.$GITHUB_RUN_NUMBER
          docker push $IMAGE_ID:$CURRENT_DATETIME.$GITHUB_RUN_NUMBER

          TAG_SUFFIX="latest"
          docker tag ${{ inputs.image_name }} $IMAGE_ID:$TAG_SUFFIX
          docker push $IMAGE_ID:$TAG_SUFFIX