name: test

on:
  workflow_call:
    inputs:
      docker_files_name:
        required: true
        type: string
      version:
        required: true
        type: string
      user:
        required: true
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
            docker build \
             --build-arg VERSION=${{ inputs.version }} \
             --build-arg P4USER=${{ inputs.user }} \
            -f ./build/${{ inputs.docker_files_name }} ./build
